version: "3.3"
volumes:
  my-volume:
    external: true
networks:
  mt-network:
    driver: bridge
  default:
services:  
  frontend:
    build : .
    container_name: products-vuejs 
    ports:
      - 8050:80
    networks:
      - mt-network